name: Build Safari Extension
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Bepp
        run: npm install -g @bepp/bepp
      - name: Build Safari Extension
        run: bepp build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PX-Downloader-Safari
          path: ./src/
